# This file contains:
# An otel-collector 'dynatrace-otelcol-config' configuration that 
#  - scrapes all pods with 
#    - name "slow-webserver.*"
#    - metrics.dynatrace.com/scrape=True annotation
#    - container port 8445 exposed
#  - adds dt_kubernetes_cluster_id (to enable context creation on Dynatrace)
#  - adds other k8s specific labels
#  - translates labels from Prometheus naming schema to Dynatrace (e.g. "." vs "_")
#  - exports all metrics via Prometheus and Dynatrace (you have to provide your Dynatrace endpoint and API Token in a secret called dynatrace-otelcol-dt-api-credentials)
# A deployment with the official opentelemetry collector (-contrib)
# A service account + clusterrole that enables the collector to access k8s API to gather endpoints and pod info 
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynatrace-otelcol-config
data:
  otel-collector-config: |
      processors:
        metricstransform:
        # transforms is a list of transformations with each element transforming a metric selected by metric name
          transforms:
            - include: ".*"
              # match_type specifies whether the include name should be used as a strict match or regexp match, default = strict
              match_type: regexp
              action: update
              operations:
                - action: update_label
                  label: k8s_container_name
                  new_label: k8s.container.name
                - action: update_label
                  label: dt_kubernetes_cluster_id
                  new_label: dt.kubernetes.cluster.id
                - action: update_label
                  label: k8s_pod_name
                  new_label: k8s.pod.name
                - action: update_label
                  label: k8s_pod_uid
                  new_label: k8s.pod.uid
                - action: update_label
                  label: dt_kubernetes_cluster_id
                  new_label: dt.kubernetes.cluster_id
                - action: update_label
                  label: dt_kubernetes_workload_kind
                  new_label: dt.kubernetes.workload.kind
                - action: update_label
                  label: dt_kubernetes_workload_name
                  new_label: dt.kubernetes.workload.name
                - action: update_label
                  label: k8s_node_name
                  new_label: k8s.node.name
                - action: update_label
                  label: k8s_namespace_name
                  new_label: k8s.namespace.name
                - action: update_label
                  label: k8s_label_name
                  new_label: k8s.label.name
                - action: update_label
                  label: k8s_label_app
                  new_label: k8s.label.app
      exporters:
        logging:
        prometheus:
          endpoint: "0.0.0.0:8889" # TODO: if desired, remove prometheus exporter from otel collector
        dynatrace:
          prefix: dynatrace_otelcol_example # TODO: Set prefix or remove completely
          endpoint: "${DT_API_ENDPOINT}/api/v2/metrics/ingest"
          # Token must at least have the Ingest metrics (metrics.ingest) permission
          api_token: "${DT_API_TOKEN}"
      extensions:
        health_check: {}
      receivers:
        prometheus:
          config:
            global:
              external_labels:
              # TODO: Set UID of kube-system namespace here!
                dt_kubernetes_cluster_id: cc84ba97-8579-4b02-8943-93e09bd446d9
            scrape_configs:
              - job_name: scrape_endpoints_with_token # TODO: Set job name
                metrics_path: /metrics

                scheme: http # TODO: Set scheme

                authorization:
                  credentials: mybearertoken # TODO: credentials. default is "bearer" authentication

                kubernetes_sd_configs:
                  - role: pod
                    api_server: https://kubernetes.default:443
                    authorization:
                      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                    tls_config:
                      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                relabel_configs:
      # part 1: Configure what to scrape
                # Scrape config: scrape only pods with metrics.dynatrace.com/scrape=True
                  - source_labels: [__meta_kubernetes_pod_annotation_metrics_dynatrace_com_scrape]
                    action: keep
                    regex: true
                # TODO: Set pod names and ports to scrape
                # Scrape config: select only pods with the given name
                  - source_labels: [__meta_kubernetes_pod_name]
                    action: keep
                    regex: "slow-webserver.*"
                # Scrape config: Per default, all containerPorts are scraped; we only want to scrape 8445
                  - source_labels: [__meta_kubernetes_pod_container_port_number]
                    action: keep
                    regex: 8445
      # part 2: Configure enrichment
                  - source_labels: [__meta_kubernetes_pod_container_name]
                    action: replace
                    target_label: "k8s_container_name"
                  - source_labels: [__meta_kubernetes_pod_name]
                    action: replace
                    target_label: "k8s_pod_name"
                  - source_labels: [__meta_kubernetes_pod_uid]
                    action: replace
                    target_label: "k8s_pod_uid"
                  - source_labels: [ __meta_kubernetes_pod_controller_kind]
                    action: replace
                    target_label: "dt_kubernetes_workload_kind"
                  - source_labels: [ __meta_kubernetes_pod_controller_name]
                    action: replace
                    target_label: "dt_kubernetes_workload_name"
                  - source_labels: [__meta_kubernetes_pod_node_name]
                    action: replace
                    target_label: "k8s_node_name"
                  - source_labels: [__meta_kubernetes_namespace]
                    action: replace
                    target_label: "k8s_namespace_name"
                  - source_labels: [__meta_kubernetes_pod_label_name]
                    action: replace
                    target_label: "k8s_label_name"
                  - source_labels: [__meta_kubernetes_pod_label_app]
                    action: replace
                    target_label: "k8s_label_app"
      service:
        telemetry:
          logs:
            level: "debug"  #TODO set log to info
        extensions:
          - health_check
        pipelines:
          metrics:
            exporters:
              - dynatrace
              - prometheus
              - logging
            processors: [metricstransform]
            receivers:
              - prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-otelcol
spec:
  selector:
    matchLabels:
      app: dynatrace-otelcol
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      labels:
        app: dynatrace-otelcol
    spec:
      serviceAccountName: dynatrace-otelcol
      containers:
        - args: ["--config", "/conf/otel-collector-config.yaml"]
          env:
            - name: GOGC
              value: "80"
            - name: DT_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: dynatrace-otelcol-dt-api-credentials
                  key: api-endpoint
            - name: DT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace-otelcol-dt-api-credentials
                  key: api-token
          image: otel/opentelemetry-collector-contrib:0.46.0
          name: otel-collector
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 8889 # Default endpoint for querying metrics of prometheus exporter.
          volumeMounts:
            - name: dynatrace-otelcol-config
              mountPath: /conf
          livenessProbe:
            httpGet:
              path: /
              port: 13133 # Health Check extension default port.
          readinessProbe:
            httpGet:
              path: /
              port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: dynatrace-otelcol-config
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: dynatrace-otelcol-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: dynatrace
  name: dynatrace-otelcol
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-otelcol
rules:
  - apiGroups: [""]
    resources: ["nodes", "services", "pods"]
    verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: dynatrace-otelcol
subjects:
- kind: ServiceAccount
  name: dynatrace-otelcol
  namespace: dynatrace
roleRef:
  kind: ClusterRole
  name: dynatrace-otelcol
  apiGroup: rbac.authorization.k8s.io